fix up foldmarkers

diff --git a/wifish b/wifish
--- a/wifish
+++ b/wifish
@@ -1,7 +1,13 @@
 #!/bin/sh
 : ${AWK_LOCATION:="/var/lib/wifish"}
 : ${SCAN_SECONDS:=5}
-: ${cli:=wpa_cli}
+: ${wpa_cli:=wpa_cli}
+which ${wpa_cli} >/dev/null 2>&1 # {{{ Make sure we have wpa_cli for those people who skipped "Requirements"
+if [ $? -ne 0 ]; then
+	echo "FAIL & BAIL: '${wpa_cli}' not available" >&1
+	exit 127
+fi # }}}
+
 if [ ! -r "${AWK_LOCATION}"/wscanparse.awk ];then # {{{ # Make sure the awk libs are found
 	echo "WARNING: Unable to find wscanparse.awk at ${AWK_LOCATION}, trying in ./awk" >&2
 	AWK_LOCATION=./awk
@@ -30,7 +36,7 @@ cli() { # {{{ # Wrapper for wpa_cli
 		fi
 		return
 	fi # }}}
-	${cli} "$@"
+	${wpa_cli} "$@"
 } # }}}
 
 scan_results() { # {{{ # Scans for APs or shows scanned results. Writes to $stemp, a tempfile
@@ -57,6 +63,7 @@ scan_results() { # {{{ # Scans for APs or shows scanned results. Writes to $stem
 } # }}}
 
 get_password() { # {{{ # Get a password interactively
+	_pret=0
 	_msg="Passphrase for '$_ss'"
 	which dialog >/dev/null 2>&1
 	if [ $? -ne 0 ];then # {{{ # No dialog, text only
@@ -67,14 +74,10 @@ get_password() { # {{{ # Get a password interactively
 		printf "\n" >&2 # }}}
 	else # {{{ # Dialog passphrase prompt
 		_psk=$(dialog --insecure --ok-label "Try It" --cancel-button "Bail" --stdout --title "Secret Stuff" --clear --passwordbox "$_msg" 0 0)
-		_press=$?
-		clear
-		if [ $_press -ne 0 ];then # {{{ User cancelled. Bail.
-			echo "Bailing at your request. What a waste of time that was ..."
-			exit
-		fi # }}}
+		_pret=$?
 	fi # }}}
 	echo $_psk
+	return $_pret
 } # }}}
 
 save_config() { # {{{ # Runs wpa_cli save_config
@@ -96,7 +99,7 @@ scan_hidden() { # {{{ # Ask if we want to try to connect to a hidden SSID
 	_yesno=""
 	cat $_tfile
 	printf "WARNING: Cannot find '$_ssid' in scan results, if it's hidden we can continue. Continue? (y/N): "
-	read yesno
+	read _yesno
 	echo $_yesno|egrep -q '^[Yy]'
 	if [ $? -eq 0 ];then
 		echo "Ok, your call"
@@ -111,6 +114,10 @@ wpa_encrypt() { # {{{ # Handle Encryption
 	__us="$1"
 	__net="$2"
 	__psk=$(get_password)
+	if [ $? -ne 0 ];then # {{{ User cancelled. Bail.
+		echo "Bailing at your request. What a waste of time that was ..."
+		exit 69
+	fi # }}}
 	_res=1
 	cli set_network $_net key_mgmt WPA-PSK > /dev/null
 	echo $__us|egrep -q 'WPA2-PSK'
@@ -203,7 +210,7 @@ connect() { # {{{ # Connect to an SSID
 	fi
 } # }}}
 
-menu() { # {{{ Menu of scan resulst to choose an AP from
+menu() { # {{{ Menu of scan results to choose an AP from
 	which dialog > /dev/null 2>&1
 	if [ $? -ne 0 ];then
 		list
@@ -245,8 +252,7 @@ $0 [options] COMMAND [arguments]
 	HERE
 } # }}}
 
-# {{{ Option Parsing
-while getopts ":h" opt; do
+while getopts ":h" opt; do # {{{ # Option Parsing
 	case $opt in
 		\?) echo "Invalid Option: -$OPTARG" >&2
 		    usage
@@ -265,8 +271,7 @@ done
 
 COMMAND=$1
 
-# {{{ Run a Command
-case $COMMAND in
+case $COMMAND in # {{{ # Run a Command
 	l|li|lis|list|"") list
 	      ;;
 	c|co|con|conn|conne|connec|connect) shift
@@ -282,4 +287,4 @@ case $COMMAND in
 	   ;;
 esac
 # }}}
-# vim: foldmethod=marker
+# vim: foldmethod=marker noet sts=8 ts=8 sw=8 syntax=sh
