use correct variable in message

diff --git a/wifish b/wifish
--- a/wifish
+++ b/wifish
@@ -10,7 +10,7 @@ fi # }}}
 
 if ! ${wpa_cli} status >/dev/null 2>&1;then # {{{ # Check that we can use wpa_cli
 	res=$?
-	echo "FATAL: Cannot get wifi status (see $cli status)" >&2
+	echo "FATAL: Cannot get wifi status (see '$wpa_cli' status)" >&2
 	exit $res
 fi # }}}
 
